name: 'Files in commit(range)'
description: 'CSV list of files in the given commit'
branding:
  icon: 'list'
  color: 'green'
inputs:
  baseSha:
    description: 'Base SHA'
    required: false
  headSha:
    description: 'Head SHA'
    required: false
outputs:
  files:
    description: 'CSV list of files in the given commit or diff between both SHA's'
runs:
  using: 'docker'
  image: 'Dockerfile'