FROM ghcr.io/wyrihaximusnet/php:7.4-zts-alpine3.12-dev-root AS runtime

RUN mkdir /workdir
COPY ./list-files.php /workdir
COPY ./composer.json /workdir
COPY ./composer.lock /workdir
WORKDIR /workdir

RUN composer install --ansi --no-progress --no-interaction --prefer-dist

ENTRYPOINT ["php", "/workdir/list-files.php"]
